name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
          working-directory: '${{ github.workspace }}/docs'
      - name: Build with Jekyll
        run: |
          bundle update
          bundle exec jekyll build #bundle update #bundle exec jekyll build
      - name: Push Checkout Folders Gemfile.lock To My Repo
        run: | 
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'
          git add ./Projects-Of-PB/docs/Gemfile.lock
          git commit -m 'Update Gemfile.lock'
          git push
